export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const CLIENT_CART_REQUEST = "CLIENT_CART_REQUEST";
export const CLIENT_CART_SUCCESS = "CLIENT_CART_SUCCESS";
export const CLIENT_CART_FAIL = "CLIENT_CART_FAIL";

export const PRODUCT_CART_REQUEST = "CLIENT_CART_REQUEST";
export const PRODUCT_CART_SUCCESS = "CLIENT_CART_SUCCESS";
export const PRODUCT_CART_FAIL = "CLIENT_CART_FAIL";

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";

export const SHOP_REQUEST = "SHOP_REQUEST";
export const SHOP_SUCCESS = "SHOP_SUCCESS";
export const SHOP_FAIL = "SHOP_FAIL";

export const ORDERS_LIST_REQUEST = "ORDERS_LIST_REQUEST";
export const ORDERS_LIST_SUCCESS = "ORDERS_LIST_SUCCESS";
export const ORDERS_LIST_FAIL = "ORDERS_LIST_FAIL";

export const UPLOAD_PRODUCT_REQUEST = "UPLOAD_PRODUCT_REQUEST";
export const UPLOAD_PRODUCT_SUCCESS = "UPLOAD_PRODUCT_SUCCESS";
export const UPLOAD_PRODUCT_FAIL = "UPLOAD_PRODUCT_FAIL";

export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";